# temp stage
FROM python:3.11-slim as builder

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

COPY requirements.txt .
RUN pip install -r requirements.txt

#Expose the required port
EXPOSE 8501

#Run the command
# CMD ["streamlit ", "run", "app.py"]

CMD streamlit run app.py

