name: Container CI
on: 
  push:
  workflow_dispatch:

env: 
  ACR_LOGON_SERVER: ${{secrets.AZ_CONTAINER_REGISTRY_NAME}}
  IMAGE_NAME: ${{secrets.AZ_CONTAINER_REGISTRY_NAME}}.azurecr.io/aoai/pdf-chat-app:${{github.sha}}

jobs:
  
  build-deploy-image:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: 'Build & Push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.ACR_LOGON_SERVER}}
          username: ${{secrets.AZ_CONTAINER_REGISTRY_USER}}
          password: ${{secrets.AZ_CONTAINER_REGISTRY_PWD}}

      - run: docker build . -t ${{env.IMAGE_NAME}} -f ./dockerfile

      - run: docker push ${{env.IMAGE_NAME}}
          
      
    
